### ISSUE TITLE
doesn't preview .jpg and some .png's

### ISSUE THREAD

**Issue by qrockz** [Sonico98/allmytoes.yazi#1]
- Yazi 0.2.4 (f6f2c30 2024-03-28)
- allmytoes 0.2.0

![prev](https://github.com/Sonico98/allmytoes.yazi/assets/56853194/29e0a447-401f-41e1-bf42-123ce59834a2)
yazi.toml 
```
[[plugin.prepend_previewers]]
mime = "image/*"
run = "allmytoes"

[[plugin.prepend_preloaders]]
mime = "image/*"
run = "allmytoes"
```

**Comment by Sonico98** [comment]
Does the output of `file --mime-type <non-working-file.jpeg>` return `image/jpeg`?
If it doesn't, try installing [mime.yazi](https://github.com/DreamMaoMao/mime.yazi) and see if it works.

**Comment by qrockz** [comment]
> Does the output of `file --mime-type <non-working-file.jpeg>` return `image/jpeg`? If it doesn't, try installing [mime.yazi](https://github.com/DreamMaoMao/mime.yazi) and see if it works.

```
$ file --mime-type lazy.jpg 
lazy.jpg: image/jpeg
```

I'v now installed mime.yazi as you have recommended but the issue still exist :sob:

**Comment by Sonico98** [comment]
> > Does the output of `file --mime-type <non-working-file.jpeg>` return `image/jpeg`? If it doesn't, try installing [mime.yazi](https://github.com/DreamMaoMao/mime.yazi) and see if it works.
> 
> ```
> $ file --mime-type lazy.jpg 
> lazy.jpg: image/jpeg
> ```
> 
> I'v now installed mime.yazi as you had recommended but the issue still exist 😭

Are you able to run allmytoes directly?
allmytoes path/to/file

**Comment by qrockz** [comment]
```
~/Pictures$ allmytoes lazy.jpg 
/home/t/.cache/thumbnails/large/a51265144e1afd5c5cf609c02be09389.png
```

**Comment by Sonico98** [comment]
What terminal are you using? Does the default previewer work? Are files being written to yazi's cache_dir (/tmp/yazi by default)? Could you share the output of ~/.local/state/yazi/yazi.log?

**Comment by qrockz** [comment]
default previewer works
terminal kitty 0.33.1
ueberzug is installed

```
$ ll /tmp/yazi
total 420K
drwxrwxr-x 1 t    t     768 Mär 31 22:11 .
drwxrwxrwt 1 root root 2,2K Apr  1 00:00 ..
-rw-rw-r-- 1 t    t     14K Mär 31 22:08 17abf4168df256edeb513af95b981021
-rw-rw-r-- 1 t    t     21K Mär 31 22:08 327b33ecfa56f4046f3eb14ab415c065
-rw-rw-r-- 1 t    t    8,9K Mär 31 22:08 338d062375e1532c7c3ed924b65fe9d4
-rw-rw-r-- 1 t    t    127K Mär 31 22:11 52eee4c26910d9bfa1e9e9fca8b07f0e
-rw-rw-r-- 1 t    t    8,8K Mär 31 22:08 776b07e3609d7cc4b504c3f7a3c6b45c
-rw-rw-r-- 1 t    t    6,9K Mär 31 22:08 93392d57b3bb05d38d8fd9af7d961293
-rw-rw-r-- 1 t    t     38K Mär 31 22:08 a5c1bf84b70b6bdba01f008b1a02cf0a
-rw-rw-r-- 1 t    t     29K Mär 31 22:08 aa02045914496fcc7d04604938e82c97
-rw-rw-r-- 1 t    t     14K Mär 31 22:10 b2437fd243f87a97147fe0c8cf5d8726
-rw-rw-r-- 1 t    t     64K Mär 31 22:08 b4c1167b7d0edc0e8a7a1dd5911cb73f
-rw-rw-r-- 1 t    t     40K Mär 31 22:08 f961cc7a6a2ba5dd35eb320d3cb677d0
-rw-rw-r-- 1 t    t     25K Mär 31 22:08 fef78884a02bc28f3594628161bc84cd
```
~/.local/state/yazi/yazi.log
```
2024-03-31T22:42:40.022544Z ERROR yazi_scheduler::preload::preload: Preload task `image` returned 2
    at yazi-scheduler/src/preload/preload.rs:42

  2024-03-31T22:42:40.038083Z ERROR yazi_plugin::utils::log: "Could not obtain thumbnail for /home/t/magick.miff. allmytoes output: ERROR [allmytoes] Could not identify MIME type of input file.\n"
    at yazi-plugin/src/utils/log.rs:20

  2024-03-31T22:42:40.038141Z ERROR yazi_scheduler::preload::preload: Preload task `allmytoes` returned 0
    at yazi-scheduler/src/preload/preload.rs:42

  2024-03-31T22:42:42.120699Z ERROR yazi_plugin::utils::log: "Could not obtain thumbnail for /home/t/magick.miff. allmytoes output: ERROR [allmytoes] Could not identify MIME type of input file.\n"
    at yazi-plugin/src/utils/log.rs:20

  2024-03-31T22:42:44.583112Z ERROR yazi_plugin::isolate::peek: error converting Lua string to &str (invalid utf-8 sequence of 1 bytes from index 0)
stack traceback:
	[C]: in function 'Url'
	[string "yazi-plugin/src/isolate/peek.rs:29:21"]:15: in function <[string "yazi-plugin/src/isolate/peek.rs:29:21"]:3>

    at yazi-plugin/src/isolate/peek.rs:50

  2024-03-31T22:42:45.456877Z ERROR yazi_plugin::isolate::peek: error converting Lua string to &str (invalid utf-8 sequence of 1 bytes from index 0)
stack traceback:
	[C]: in function 'Url'
	[string "yazi-plugin/src/isolate/peek.rs:29:21"]:15: in function <[string "yazi-plugin/src/isolate/peek.rs:29:21"]:3>

    at yazi-plugin/src/isolate/peek.rs:50

  2024-03-31T22:42:49.572858Z ERROR yazi_plugin::isolate::peek: error converting Lua string to &str (invalid utf-8 sequence of 1 bytes from index 0)
stack traceback:
	[C]: in function 'Url'
	[string "yazi-plugin/src/isolate/peek.rs:29:21"]:15: in function <[string "yazi-plugin/src/isolate/peek.rs:29:21"]:3>

    at yazi-plugin/src/isolate/peek.rs:50

  2024-03-31T22:42:55.339915Z ERROR yazi_plugin::isolate::peek: error converting Lua string to &str (invalid utf-8 sequence of 1 bytes from index 0)
stack traceback:
	[C]: in function 'Url'
	[string "yazi-plugin/src/isolate/peek.rs:29:21"]:15: in function <[string "yazi-plugin/src/isolate/peek.rs:29:21"]:3>

    at yazi-plugin/src/isolate/peek.rs:50

  2024-03-31T22:42:55.506555Z ERROR yazi_plugin::isolate::peek: error converting Lua string to &str (invalid utf-8 sequence of 1 bytes from index 0)
stack traceback:
	[C]: in function 'Url'
	[string "yazi-plugin/src/isolate/peek.rs:29:21"]:15: in function <[string "yazi-plugin/src/isolate/peek.rs:29:21"]:3>

    at yazi-plugin/src/isolate/peek.rs:50
```

**Comment by Sonico98** [comment]
Everything looks fine... how weird. The only error that shows up in the log corresponds to a "magick.miff" file, which allmytoes can't process because it's not an image file.
Could you contact me over at [Telegram](t.me/Sonico98) or Discord (sonico98)? Or suggest some other channel that offers instant communication.

**Comment by qrockz** [comment]
I've send you friendship request in Discord.

**Comment by Sonico98** [comment]
Turns out this is a [known yazi bug](https://discord.com/channels/1136203602898194542/1136203604076802092/1228022647384703037) (links to a message on yazi's Discord server). It should get fixed in the near future, but until then, prefer defining your preloaders / previewers manually rather than using `prepend_preloaders` and `prepend_previewers` in your config file.
1. Copy all the previewers and preloaders from the [default yazi config](https://github.com/sxyazi/yazi/blob/b10f2de16d46df3ed7f6efe99ac966fd49d6e919/yazi-config/preset/yazi.toml#L86).
2. Change the preloader and previewer for `mime = image/*` from `image` to `allmytoes`.
