### ISSUE TITLE
installtion issue.

### ISSUE THREAD

**Issue by NormTurtle** [Sonico98/allmytoes.yazi#2]
why its not in AUR?
im not gonan install CARGO/rust for it

**Comment by Sonico98** [comment]
Hi, I'm not the creator of allmytoes.
You can grab a prebuilt binary from [here](https://gitlab.com/allmytoes/allmytoes/-/releases) if you want to avoid compiling it yourself. You may also write a PKGBUILD for it and submit it to the AUR.
